[tool.poetry]
name = "openpack-toolkit"
version = "0.3.0"
description = "Toolkit for OpenPack Dataset"
authors = ["Yoshimura Naoya"]
homepage = "https://open-pack.github.io"
repository = "https://github.com/open-pack/open-pack-toolkit"
readme = "README.md" 
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.11"
numpy = "<1.22.0"
pandas = ">=1.2.4"
sklearn = ">=0.0"
omegaconf = "^2.2.2"

[tool.poetry.dev-dependencies]
pytest = ">=6.2.4"
pytest-cov = "^3.0.0"
pdoc3 = "^0.10.0"
Jinja2 = "^3.1.2"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py37", "py38", "py39"]

[tool.isort]
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
force_single_line = false
include_trailing_comma = true
line_length = 100
multi_line_output = 3
use_parentheses = true
