schema: ImuConfig
name: atr-qags
description: Acceleration, gyro, and quaternion from ATR IMU sensors
path:
  template: ${path.datasets.openpack}/{user}/{node}/{session}.csv
frame_rate: 30
nodes:
- atr01
- atr02
- atr03
- atr04
acc: true
gyro: true
quat: true
