schema: ImuConfig
name: atr-acc
description: Accelerations from ATR IMU sensors
path:
  template: ${path.datasets.openpack}/{user}/{node}/{session}.csv
frame_rate: 30
nodes:
- atr01
- atr02
- atr03
- atr04
acc: true
gyro: false
quat: false
