schema: ImuConfig
name: atr-qags
description: Acceleration, gyro, and quaternion from ATR IMU sensors
super_stream: null
path:
  dir: ${path.openpack.rootdir}/${user.name}/atr/${device}
  fname: ${session}.csv
file_format:
  file_type: csv
  columns:
  - name: unixtime
    unit: milli second
  - name: acc_x
    unit: G
  - name: acc_y
    unit: G
  - name: acc_z
    unit: G
  - name: gyro_x
    unit: dps
  - name: gyro_y
    unit: dps
  - name: gyro_z
    unit: dps
  - name: quat_w
  - name: quat_x
  - name: quat_y
  - name: quat_z
frame_rate: 30
devices:
- atr01
- atr02
- atr03
- atr04
acc: true
gyro: true
quat: true
