generate:
	poetry run python dataset_annotation_config.py
	poetry run python dataset_split_config.py
	poetry run python dataset_stream_config.py
	poetry run python user_config.py
	poetry run python release_config.py
